# Service for the preview version (green)
apiVersion: v1
kind: Service
metadata:
  name: {{ include "web-app-chart.fullname" . }}-preview
  labels:
    {{- include "web-app-chart.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "web-app-chart.selectorLabels" . | nindent 4 }}
